# Generated by Django 4.2.1 on 2023-05-08 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="likes",
            field=models.ManyToManyField(
                related_name="like_products", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
