# Generated by Django 4.2.1 on 2023-05-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="price",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="store",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
