# Generated by Django 4.2.1 on 2023-05-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="introdution",
            new_name="introduction",
        ),
    ]
