# Generated by Django 4.2.1 on 2023-05-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_productreview_price_alter_productreview_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
